//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATC_Events()
        {
            this.ATC_Timesheet2000 = new HashSet<ATC_Timesheet2000>();
            this.ATC_Timesheet2003 = new HashSet<ATC_Timesheet2003>();
            this.ATC_Timesheet2002 = new HashSet<ATC_Timesheet2002>();
            this.ATC_Timesheet2004 = new HashSet<ATC_Timesheet2004>();
            this.ATC_Timesheet2005 = new HashSet<ATC_Timesheet2005>();
            this.ATC_Timesheet2006 = new HashSet<ATC_Timesheet2006>();
            this.ATC_Timesheet2007 = new HashSet<ATC_Timesheet2007>();
            this.ATC_Timesheet2008 = new HashSet<ATC_Timesheet2008>();
            this.ATC_Timesheet2009 = new HashSet<ATC_Timesheet2009>();
            this.ATC_Timesheet2011 = new HashSet<ATC_Timesheet2011>();
            this.ATC_Timesheet2012 = new HashSet<ATC_Timesheet2012>();
            this.ATC_AbsenceRequests = new HashSet<ATC_AbsenceRequests>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2000> ATC_Timesheet2000 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2003> ATC_Timesheet2003 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2002> ATC_Timesheet2002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2004> ATC_Timesheet2004 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2005> ATC_Timesheet2005 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2006> ATC_Timesheet2006 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2007> ATC_Timesheet2007 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2008> ATC_Timesheet2008 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2009> ATC_Timesheet2009 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2011> ATC_Timesheet2011 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Timesheet2012> ATC_Timesheet2012 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_AbsenceRequests> ATC_AbsenceRequests { get; set; }
    }
}
