//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATC_Employees()
        {
            this.LeaderOfStaffs = new HashSet<ATC_Employees>();
            this.ATC_SalaryStatus = new HashSet<ATC_SalaryStatus>();
            this.ATC_Timesheet2000 = new HashSet<ATC_Timesheet2000>();
            this.ATC_Timesheet2003 = new HashSet<ATC_Timesheet2003>();
            this.ATC_Timesheet2002 = new HashSet<ATC_Timesheet2002>();
            this.ATC_Timesheet2004 = new HashSet<ATC_Timesheet2004>();
            this.ATC_Timesheet2005 = new HashSet<ATC_Timesheet2005>();
            this.ATC_Timesheet2006 = new HashSet<ATC_Timesheet2006>();
            this.ATC_Timesheet2007 = new HashSet<ATC_Timesheet2007>();
            this.ATC_Timesheet2008 = new HashSet<ATC_Timesheet2008>();
            this.ATC_Timesheet2009 = new HashSet<ATC_Timesheet2009>();
            this.ATC_Timesheet2011 = new HashSet<ATC_Timesheet2011>();
            this.ATC_Timesheet2012 = new HashSet<ATC_Timesheet2012>();
            this.Authoriser1Requests = new HashSet<ATC_AbsenceRequests>();
            this.Authoriser2Requests = new HashSet<ATC_AbsenceRequests>();
            this.AbsenceRequests = new HashSet<ATC_AbsenceRequests>();
        }
    
        public int StaffID { get; set; }
        public Nullable<int> JobTitleID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
        public Nullable<int> DirectLeaderID { get; set; }
        public System.DateTime JoinDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public bool fgIndirect { get; set; }
        public Nullable<decimal> LeaveDue { get; set; }
        public string PCName { get; set; }
        public string ExtPhone { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> CSOLevel { get; set; }
        public string StaffIDHR { get; set; }
        public Nullable<decimal> JobRoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_Employees> LeaderOfStaffs { get; set; }
        public virtual ATC_Employees DirectLeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_SalaryStatus> ATC_SalaryStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2000> ATC_Timesheet2000 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2003> ATC_Timesheet2003 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2002> ATC_Timesheet2002 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2004> ATC_Timesheet2004 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2005> ATC_Timesheet2005 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2006> ATC_Timesheet2006 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2007> ATC_Timesheet2007 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2008> ATC_Timesheet2008 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2009> ATC_Timesheet2009 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2011> ATC_Timesheet2011 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<ATC_Timesheet2012> ATC_Timesheet2012 { get; set; }
        public virtual ATC_JobTitle ATC_JobTitle { get; set; }
        public virtual ATC_Department ATC_Department { get; set; }
        public virtual ATC_Preferences ATC_Preferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_AbsenceRequests> Authoriser1Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_AbsenceRequests> Authoriser2Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_AbsenceRequests> AbsenceRequests { get; set; }
        public virtual ATC_PersonalInfo PersonalInfo { get; set; }
    }
}
