//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_SalaryStatus
    {
        public int StaffID { get; set; }
        public System.DateTime SalaryDate { get; set; }
        public Nullable<int> WorkingHourID { get; set; }
        public string Salary { get; set; }
        public string SalaryTax { get; set; }
        public string Currency { get; set; }
        public string CurrencyTax { get; set; }
        public Nullable<bool> fgOverTimePay { get; set; }
        public Nullable<decimal> BankID { get; set; }
        public string AccountNo { get; set; }
        public string BankDetail { get; set; }
        public bool fgProbation { get; set; }
        public bool fgNoInsurance { get; set; }
        public string SalaryNote { get; set; }
    
        public virtual ATC_Employees ATC_Employees { get; set; }
        public virtual ATC_WorkingHours ATC_WorkingHours { get; set; }
    }
}
