//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_WorkingHours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATC_WorkingHours()
        {
            this.ATC_SalaryStatus = new HashSet<ATC_SalaryStatus>();
        }
    
        public int WorkingHourID { get; set; }
        public decimal Hours { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATC_SalaryStatus> ATC_SalaryStatus { get; set; }
    }
}
