//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_AbsenceRequests
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int StaffId { get; set; }
        public int Authoriser1_Id { get; set; }
        public Nullable<int> Authoriser2_Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Note { get; set; }
        public bool isAuthorisedByHr { get; set; }
        public bool isAuthoriser1Approved { get; set; }
        public Nullable<bool> isAuthoriser2Approved { get; set; }
        public Nullable<bool> isHrApproved { get; set; }
        public int Status { get; set; }
        public string Authoriser1Note { get; set; }
        public string Authoriser2Note { get; set; }
        public string HrNote { get; set; }
        public System.DateTime DateSubmitted { get; set; }
    
        public virtual ATC_Events ATC_Events { get; set; }
        public virtual ATC_Employees Authoriser1 { get; set; }
        public virtual ATC_Employees Authoriser2 { get; set; }
        public virtual ATC_Employees Staff { get; set; }
    }
}
