//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_Holiday
    {
        public int HolidayID { get; set; }
        public short sDay { get; set; }
        public short sMonth { get; set; }
        public int sYear { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public string Holiday { get; set; }
        public decimal ratio { get; set; }
    }
}
