//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_ProjectTracking
    {
        public int ProjTrackerID { get; set; }
        public string ProjectID { get; set; }
        public int ProjStatus { get; set; }
        public Nullable<decimal> ProposalValue { get; set; }
        public Nullable<decimal> AwardedValue { get; set; }
        public System.DateTime DateTracking { get; set; }
        public decimal StaffID { get; set; }
    }
}
