//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_Preferences
    {
        public int StaffID { get; set; }
        public string FavoriteUrl { get; set; }
        public Nullable<byte> Numofrows { get; set; }
        public string ProCriteria { get; set; }
        public string EmpCriteria { get; set; }
    
        public virtual ATC_Employees ATC_Employees { get; set; }
    }
}
