//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATC_PersonalInfo
    {
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int MarialStatus { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string PrivateEmail { get; set; }
        public string MobilePhone { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> CardDateOfIssued { get; set; }
        public string CardPlaceOfIssue { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> PassportExpire { get; set; }
        public string CurrentAddress { get; set; }
        public string EmergencyContact { get; set; }
        public string TaxCode { get; set; }
        public string InsuranceBookNo { get; set; }
        public string BankAccount1 { get; set; }
        public string BankAccount2 { get; set; }
        public string HomeAddress { get; set; }
        public string ContactVietnam { get; set; }
        public string HomeCountry { get; set; }
        public byte UserType { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MiddleName { get; set; }
        public string IDNumber { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string EmailLabel { get; set; }
        public string EmailAddress_Ex { get; set; }
        public string Website { get; set; }
        public string Note { get; set; }
        public bool fgDelete { get; set; }
    
        public virtual ATC_Employees ATC_Employees { get; set; }
        public virtual ATC_Users ATC_Users { get; set; }
    }
}
