//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        public int PersonID { get; set; }
        public string IDNumber { get; set; }
        public string Fullname { get; set; }
        public string FirstName { get; set; }
        public string lastname { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string EmailAddress { get; set; }
        public string EmailAddress_Ex { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string ExtPhone { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public string FirstNameLeader { get; set; }
        public string LastnameLeader { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<bool> fgIndirect { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> CardDateOfIssued { get; set; }
        public string CardPlaceOfIssue { get; set; }
        public string CostingGroupName { get; set; }
    }
}
