//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeaveManagementContext : DbContext
    {
        public LeaveManagementContext()
            : base("name=LeaveManagementContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATC_Employees> ATC_Employees { get; set; }
        public virtual DbSet<ATC_Timesheet> ATC_Timesheet { get; set; }
        public virtual DbSet<ATC_Events> ATC_Events { get; set; }
        public virtual DbSet<ATC_SalaryStatus> ATC_SalaryStatus { get; set; }
        public virtual DbSet<ATC_WorkingHours> ATC_WorkingHours { get; set; }
        public virtual DbSet<ATC_Holiday> ATC_Holiday { get; set; }
        public virtual DbSet<ATC_Timesheet2000> ATC_Timesheet2000 { get; set; }
        public virtual DbSet<ATC_Timesheet2001> ATC_Timesheet2001 { get; set; }
        public virtual DbSet<ATC_Timesheet2002> ATC_Timesheet2002 { get; set; }
        public virtual DbSet<ATC_Timesheet2003> ATC_Timesheet2003 { get; set; }
        public virtual DbSet<ATC_Timesheet2004> ATC_Timesheet2004 { get; set; }
        public virtual DbSet<ATC_Timesheet2005> ATC_Timesheet2005 { get; set; }
        public virtual DbSet<ATC_Timesheet2006> ATC_Timesheet2006 { get; set; }
        public virtual DbSet<ATC_Timesheet2007> ATC_Timesheet2007 { get; set; }
        public virtual DbSet<ATC_Timesheet2008> ATC_Timesheet2008 { get; set; }
        public virtual DbSet<ATC_Timesheet2009> ATC_Timesheet2009 { get; set; }
        public virtual DbSet<ATC_Timesheet2010> ATC_Timesheet2010 { get; set; }
        public virtual DbSet<ATC_Timesheet2011> ATC_Timesheet2011 { get; set; }
        public virtual DbSet<ATC_Timesheet2012> ATC_Timesheet2012 { get; set; }
        public virtual DbSet<ATC_Timesheet2013> ATC_Timesheet2013 { get; set; }
        public virtual DbSet<ATC_Timesheet2014> ATC_Timesheet2014 { get; set; }
        public virtual DbSet<ATC_Timesheet2015> ATC_Timesheet2015 { get; set; }
        public virtual DbSet<ATC_JobTitle> ATC_JobTitle { get; set; }
        public virtual DbSet<ATC_Department> ATC_Department { get; set; }
        public virtual DbSet<ATC_Functions> ATC_Functions { get; set; }
        public virtual DbSet<ATC_Group> ATC_Group { get; set; }
        public virtual DbSet<ATC_Permissions> ATC_Permissions { get; set; }
        public virtual DbSet<ATC_Users> ATC_Users { get; set; }
        public virtual DbSet<ATC_Preferences> ATC_Preferences { get; set; }
        public virtual DbSet<HR_CurrentJobtitle> HR_CurrentJobtitle { get; set; }
        public virtual DbSet<ATC_Timesheet2016> ATC_Timesheet2016 { get; set; }
        public virtual DbSet<ATC_AbsenceRequests> ATC_AbsenceRequests { get; set; }
        public virtual DbSet<ATC_EmailTemplate> ATC_EmailTemplate { get; set; }
        public virtual DbSet<HR_ReceiveReport> HR_ReceiveReport { get; set; }
        public virtual DbSet<HR_Employee> HR_Employee { get; set; }
        public virtual DbSet<ATC_PersonalInfo> ATC_PersonalInfo { get; set; }
        public virtual DbSet<ATC_Timesheet2017> ATC_Timesheet2017 { get; set; }
        public virtual DbSet<ATC_Timesheet2018> ATC_Timesheet2018 { get; set; }
        public virtual DbSet<ATC_Timesheet2019> ATC_Timesheet2019 { get; set; }
        public virtual DbSet<ATC_Timesheet2020> ATC_Timesheet2020 { get; set; }
        public virtual DbSet<ATC_Timesheet2021> ATC_Timesheet2021 { get; set; }
        public virtual DbSet<ATC_ProjectTracking> ATC_ProjectTracking { get; set; }
        public virtual DbSet<ATC_Timesheet2022> ATC_Timesheet2022 { get; set; }
        public virtual DbSet<ATC_Timesheet2024> ATC_Timesheet2024 { get; set; }
    }
}
