// <auto-generated />
namespace AIS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add__table__ATC_AbsenceRequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add__table__ATC_AbsenceRequests));
        
        string IMigrationMetadata.Id
        {
            get { return "201606100830470_add__table__ATC_AbsenceRequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
